services:
  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestioeduca
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "--password=root",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    depends_on:
      - db
    ports:
      - "9090:8080"
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/
    working_dir: /var/www/
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: gestioeduca
      DB_USERNAME: user
      DB_PASSWORD: user
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    networks:
      - app-network
    command: bash -c "chmod +x entrypoint.sh && ./entrypoint.sh"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://api.grupify.cat"]
      interval: 10s
      timeout: 10s
      start_period: 350s
      retries: 5

  queue-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-queue
    volumes:
      - ./backend:/var/www/
    working_dir: /var/www/
    depends_on:
      backend:
        condition: service_healthy
      redis:
        condition: service_started
      db:
        condition: service_started
    networks:
      - app-network
    command: php artisan queue:work redis --tries=3 --timeout=90

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - app-network

  nodejs:
    image: node:18
    container_name: nodejs-service
    working_dir: /usr/src/app
    volumes:
      - ./backend/node-app:/usr/src/app
    ports:
      - "5000:5000"
    command: bash -c "npm install && npm start"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    expose:
      - "5000"
    networks:
      - app-network

  chat:
    build:
      context: ./mcp-use-grupify
      dockerfile: Dockerfile
    container_name: grupify-chat
    ports:
      - "8501:8501"
    volumes:
      - ./mcp-use-grupify:/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: gestioeduca
      DB_USER: user
      DB_PASSWORD: user
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge
